### ISSUE TITLE
MousePort Mac Client Stuck On "Searching"

### ISSUE THREAD

**Issue by CobreDev** [iPAWiND/MousePort#1]
I've downloaded everything, and I put the dylib in /Library/MobileSubstrate/DynamicLibraries on my jailbroken iPhone. It's a 5s running iOS 12.1.2 on the Chimera jailbreak. 

When I run the app on my Mac, it stays "Searching". I haven't done anything on my iPhone besides move the dylib and png to /Library/MobileSubstrate/DynamicLibraries and respring. Is there something else I should do?

Thanks!

**Comment by jakeajames** [comment]
You're supposed to put a filter as well (.plist file), but that being said, it still doesn't work for me, stuck on searching as well, tried filtering SB and UIKit with same result.

**Comment by CobreDev** [comment]
Wow, I feel so dumb for forgetting that. Thanks! I removed it from my phone, but I may try again later. 

Are you only trying SB and UIKit, or are you also trying individual apps? Also, what jailbreak are you on

**Comment by iPAWiND** [comment]
The tweak is designed for non-jailbroken devices.
We might consider supporting jailbreak soon.

**Comment by jakeajames** [comment]
@iPAWiND it shouldn't make a single difference, injection methods change but after all it's still injection... could you elaborate more

**Comment by CobreDev** [comment]
@iPAWiND Like @jakeajames said, it shouldn't matter. How are you supposed to inject on a non-jailbroken device?

**Comment by CobreDev** [comment]
Thanks everyone, I successfully injected an ipa and got it working. @jakeajames is there any chance you could work on making this system-wide for jailbroken devices? Thanks again!
